name = "minecraft-list"
main = "src/index.ts"
compatibility_date = "2023-03-01"

workers_dev = false
routes = [
    { pattern = "src.mealuet.com/minecraft/*", zone_name = "mealuet.com" }
]

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
[[r2_buckets]]
binding = 'BUCKET_bucketname'
bucket_name = 'mealuet-src'
